--Enlazar demo_orders con demo_customer: order_id, total y nombre del cliente

SELECT ORDER_ID, ORDER_TOTAL AS "TOTAL PEDIDO", CUST_FIRST_NAME AS NOMBRE
FROM DEMO_ORDERS
LEFT JOIN DEMO_CUSTOMERS
ON DEMO_ORDERS.CUSTOMER_ID = DEMO_CUSTOMERS.CUSTOMER_ID;

--Con inner join si hubiera algun pedido sin cliente no aparecería, nisiquiera como null.

--Clientes que no tienen pedido
SELECT DEMO_CUSTOMERS.CUSTOMER_ID, CUST_FIRST_NAME, CUST_STATE
FROM DEMO_CUSTOMERS
FULL OUTER JOIN DEMO_ORDERS
ON DEMO_CUSTOMERS.CUSTOMER_ID = DEMO_ORDERS.CUSTOMER_ID
WHERE DEMO_ORDERS.CUSTOMER_ID IS NULL OR DEMO_CUSTOMERS.CUSTOMER_ID IS NULL;

--Al cliente que no tiene pedido añadirle el estado

SELECT DEMO_CUSTOMERS.CUSTOMER_ID, CUST_FIRST_NAME, CUST_STATE, DEMO_STATES.STATE_NAME
FROM DEMO_CUSTOMERS
FULL OUTER JOIN DEMO_ORDERS
ON (DEMO_CUSTOMERS.CUSTOMER_ID = DEMO_ORDERS.CUSTOMER_ID)
INNER JOIN DEMO_STATES
ON DEMO_CUSTOMERS.CUST_STATE = DEMO_STATES.ST
WHERE DEMO_ORDERS.CUSTOMER_ID IS NULL OR DEMO_CUSTOMERS.CUSTOMER_ID IS NULL;

-- Probamos a combinar dos tablas sin join
SELECT *
FROM DEMO_ORDERS, DEMO_ORDER_ITEMS
WHERE DEMO_ORDERS.ORDER_ID = DEMO_ORDER_ITEMS.ORDER_ID;
