--Subprograma que devuelva el id del mejor cliente
CREATE OR REPLACE FUNCTION mejorcliente 
RETURN NUMBER AS  
   miId DEMO_CUSTOMERS.CUSTOMER_ID%TYPE;
BEGIN    
   SELECT ID INTO miId FROM 
   (SELECT DEMO_ORDERS.CUSTOMER_ID AS ID,
   SUM(DEMO_ORDERS.ORDER_TOTAL) AS TOTAL
   FROM DEMO_ORDERS
   GROUP BY DEMO_ORDERS.CUSTOMER_ID
   ORDER BY TOTAL DESC)
   WHERE ROWNUM = 1;
   return MIiD;
END;
/
begin
   clg('El id es: ' || mejorcliente);
end;