--Subprograma que devuelva el id del mejor cliente
CREATE OR REPLACE FUNCTION mejorcliente 
RETURN NUMBER AS  
   miId DEMO_CUSTOMERS.CUSTOMER_ID%TYPE;
BEGIN    
   /* CURSOR C 
   SELECT CLIENT_ID
    FROM
    DEMO_ORDERS
    GROUP BY CLIENT_ID
    ORDER BY SUM(ORDER_TOTAL) DESC
    
    BEGIN....
    OPEN C
    FETCH C INTO BEST_CLIENT
    WHEN 
    CLOSE C;
    RETURN BEST_CLIENT*/   
   SELECT ID INTO miId FROM 
   (SELECT DEMO_ORDERS.CUSTOMER_ID AS ID,
   SUM(DEMO_ORDERS.ORDER_TOTAL) AS TOTAL
   FROM DEMO_ORDERS
   GROUP BY DEMO_ORDERS.CUSTOMER_ID
   ORDER BY TOTAL DESC)
   WHERE ROWNUM = 1;
   return MIiD;
END;
/
begin
   clg('El id es: ' || mejorcliente);
end;