SELECT ORDER_ID, DEMO_ORDER_ITEMS.PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, QUANTITY, UNIT_PRICE * QUANTITY AS TOTAL
FROM DEMO_ORDER_ITEMS
LEFT JOIN DEMO_PRODUCT_INFO
ON DEMO_ORDER_ITEMS.PRODUCT_ID = DEMO_PRODUCT_INFO.PRODUCT_ID; 